"""WebFetch (LangGraph agent) Pydantic models."""

import hashlib
from typing import Any, List, Literal, Optional

from pydantic import BaseModel, Field, computed_field

from .judge import JudgeVerdict
from .search import SearchResponse


class SearchQueryList(BaseModel):
    """List of search queries generated by LLM."""

    queries: list[str] = Field(..., description="List of search queries")


class URLSelectionItem(BaseModel):
    """Single URL selection with metadata."""

    url: str = Field(..., description="URL to select")
    priority: int = Field(default=1, ge=1, le=5, description="Priority level 1-5")
    reason: str = Field(..., description="Reason for selecting this URL")


class URLSelectionList(BaseModel):
    """List of selected URLs."""

    urls: list[URLSelectionItem] = Field(..., description="List of selected URLs")


class FeatureSet(BaseModel):
    """Atomic features extracted from content with quotes."""

    features: list[str] = Field(default_factory=list, description="List of features")
    sources: list[str] = Field(default_factory=list, description="List of source URLs")


class SourceFeature(BaseModel):
    """Source with its features for final output."""

    url: str = Field(..., description="URL of the source")
    text: str = Field(default="", description="Text content from this source")
    features: List[str] = Field(
        default_factory=list, description="Features extracted from this source"
    )


class WebFetchState(BaseModel):
    """LangGraph state for webfetch agent."""

    prompt: str
    tenant_id: str
    version: str = "1.0"

    # Checkpoint integration (Epic 3 AC1)
    checkpoint_id: str = ""
    checkpoint_store: Any = None

    # Configuration parameters
    gen_srch_q_cnt: int = Field(
        default=5, ge=3, le=10, description="Number of search queries to generate"
    )
    sel_top_level: int = Field(
        default=20, ge=5, le=50, description="Number of URLs to select"
    )
    output_format: Literal["markdown", "json"] = Field(
        default="markdown",
        description="Output format for webfetch results (default: markdown)",
    )

    # Search phase
    search_queries: list[str] = []
    search_results: list[SearchResponse] = []

    # URL selection phase
    selected_urls: list[URLSelectionItem] = []

    # Content fetch phase
    fetched_content: list[dict] = []

    # Feature extraction phase
    features: Optional[FeatureSet] = None

    # Judge results
    url_judgment: Optional[JudgeVerdict] = None
    feature_judgment: Optional[JudgeVerdict] = None

    # Fallback flag
    fallback_applied: bool = False

    # Cache key for full response
    cache_key: Optional[str] = None

    # Content freshness score (Epic 4)
    freshness_score: float = Field(default=0.75, ge=0.0, le=1.0)

    # Final result structure
    final_result: Optional[str] = None  # Aggregated result
    sources_with_features: list[SourceFeature] = []  # Sources with their features

    @computed_field
    def checkpoint_key(self) -> str:
        """Generate checkpoint key for LangGraph checkpointing.

        Uses cache_key if present, otherwise generates from prompt + tenant_id + version.
        Key format: ``webfetch_checkpoint:{tenant_id}:{version}:{cache_key}``.

        This is a read-only computed field — it does not mutate self.cache_key.
        """
        if self.cache_key:
            return (
                f"webfetch_checkpoint:{self.tenant_id}:{self.version}:{self.cache_key}"
            )

        raw = f"{self.prompt}:{self.tenant_id}:{self.version}"
        key = hashlib.sha256(raw.encode()).hexdigest()[:16]
        return f"webfetch_checkpoint:{self.tenant_id}:{self.version}:{key}"
